travis:
  secure:
    BINSTAR_TOKEN: QBpsIQVnAPkzyp1g2LLGFt/WDL4mknUiGS6VMs3uKzDPrtJ7iXDFxMwXP3grSzE4Sst1RqZg4Bl5W28yfVrGFErWYt59fPxJRUOvLHYRpIWx8JxpV7Bm73AQPOYOVNq2FI8NSYXtj+rGRY4THjueCU0nqUgfKcciCfpnthqhgeLw1Mr57Pou+o79sbEUE7+cpO8IYG0oGzkhySwZ7ibwDm6gtdLlaYcVpNY9wCAyJQyurIw786ygf2XOKfww8uruNcnmoqYp5suUxWZkUPSodnr3HcmFWG5W5JwxEa5AxV1LXG3Ew1rUAX4YvbVCQLZo9co8MOR4l9UHcrWx0YhfMohlUzhxBaZm+JQbW47iYYBj/sO5sEAjUc0c0bez/k0WbqWOiMiAUTknlayjJcPceOprLf5t0sVkGpBbZpzEpt5xXaYME/EolROkzz/awBZ+1dnP0vLhZeDEcxvo9MdfRa5mOAesavAJoGNBGaYvZQdyggWoUgcImYMQqx1cgO4B0m7L2mIfLX2hA89KtNXKK83gm0sJa7LKGy7VHTBXV/bxMoqMk46l9eBQAK96Yyp5DmOENv68ZlvfOo36Egrwgz6JIsIrSSb3s29kX7TzNUCZl1pWepKVI/rtJM4MNGS9WPNxbz3xoCZiQmDSV2miLRBitXz4WNAAX0NfXhF9Po0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
